USE [master]
GO

/****** Object:  Database [SolutionsTest]    Script Date: 11/4/2019 2:45:16 PM ******/
CREATE DATABASE [SolutionsTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SolutionsTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SolutionsTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SolutionsTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SolutionsTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SolutionsTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SolutionsTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SolutionsTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SolutionsTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SolutionsTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SolutionsTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [SolutionsTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SolutionsTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SolutionsTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SolutionsTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SolutionsTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SolutionsTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SolutionsTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SolutionsTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SolutionsTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SolutionsTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SolutionsTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SolutionsTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SolutionsTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SolutionsTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SolutionsTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SolutionsTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SolutionsTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SolutionsTest] SET RECOVERY FULL 
GO

ALTER DATABASE [SolutionsTest] SET  MULTI_USER 
GO

ALTER DATABASE [SolutionsTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SolutionsTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SolutionsTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SolutionsTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SolutionsTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SolutionsTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SolutionsTest] SET  READ_WRITE 
GO

